from tau2.utils.utils import DATA_DIR

RESTAURANT_DATA_DIR = DATA_DIR / "tau2" / "domains" / "restaurant"
RESTAURANT_DB_PATH = RESTAURANT_DATA_DIR / "db.json"
RESTAURANT_POLICY_PATH = RESTAURANT_DATA_DIR / "policy.md"
RESTAURANT_TASK_SET_PATH = RESTAURANT_DATA_DIR / "tasks.json"
